patterns/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.PatternList.as_view(), name='home'),
    path('favourite/', views.favourite_view, name='favourite'),
    path('post/', views.post_pattern, name='post_pattern'),
    path('<slug:slug>/', views.pattern_detail, name='pattern_detail'),
    path('<slug:slug>/toggle-favourite/',
         views.toggle_favourite, name='toggle_favourite'),
    path('<slug:slug>/edit-comment/<int:comment_id>',
         views.edit_comment, name='edit_comment'),
    path('<slug:slug>/delete-comment/<int:comment_id>',
         views.delete_comment, name='delete_comment'),
]

stitchin/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("accounts/", include("allauth.urls")),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('patterns.urls'), name='patterns-urls'),
]

patterns/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField


DIFFICULTY_LEVEL = (
    (0, 'Easy'),
    (1, 'Medium'),
    (2, 'Hard')
)

CRAFT = (
    (0, 'Crochet'),
    (1, 'Knitting')
)

WEIGHT = (
    (0, 'Lace/2 ply'),
    (1, 'Light Fingering/3 ply'),
    (2, 'Fingering/4 ply (14 wpi)'),
    (3, 'Sport/5 ply (12 wpi)'),
    (4, 'DK/8 ply (11 wpi)'),
    (5, 'Aran/10 ply (8 wpi)'),
    (6, 'Chunky/12 ply (7 wpi)'),
    (7, 'Super Chunky/16 ply (5-6 wpi)')
)

HOOK_NEEDLE_TYPE = (
    (0, 'Hook'),
    (1, 'Needle')
)

HOOK_SIZE = (
    (0, '2.0 mm'),
    (1, '2.25 mm'),
    (2, '2.5 mm'),
    (3, '2.75 mm'),
    (4, '3.0 mm'),
    (5, '3.25 mm'),
    (6, '3.5 mm'),
    (7, '3.75 mm'),
    (8, '4.0 mm'),
    (9, '4.5 mm'),
    (10, '5.0 mm'),
    (11, '5.5 mm'),
    (12, '6.0 mm'),
    (13, '6.5 mm'),
    (14, '7.0 mm'),
    (15, '8.0 mm'),
    (16, '9.0 mm'),
    (17, '10.0 mm'),
    (18, '12.0 mm'),
    (19, '15.0 mm'),
    (20, '20.0 mm')
)

NEEDLE_SIZE = (
    (0, '2.0 mm / US 0'),
    (1, '2.25 mm / US 1'),
    (2, '2.5 mm / US 1.5'),
    (3, '2.75 mm / US 2'),
    (4, '3.0 mm / US 2.5'),
    (5, '3.25 mm / US 3'),
    (6, '3.5 mm / US 4'),
    (7, '3.75 mm / US 5'),
    (8, '4.0 mm / US 6'),
    (9, '4.5 mm / US 7'),
    (10, '5.0 mm / US 8'),
    (11, '5.5 mm / US 9'),
    (12, '6.0 mm / US 10'),
    (13, '6.5 mm / US 10.5'),
    (14, '7.0 mm / US 10.75'),
    (15, '8.0 mm / US 11'),
    (16, '9.0 mm / US 13'),
    (17, '10.0 mm / US 15'),
    (18, '12.0 mm / US 17'),
    (19, '15.0 mm / US 19'),
    (20, '20.0 mm / US 36')
)

SIZE = (
    (0, 'One Size'),
    (1, 'XS'),
    (2, 'S'),
    (3, 'M'),
    (4, 'L'),
    (5, 'XL')
)

CATEGORY = (
    (0, 'Clothing'),
    (1, 'Accessories'),
    (2, 'Toys and Hobbies'),
    (3, 'Pet'),
    (4, 'Home')
)


class Pattern(models.Model):
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="patterns"
    )
    title = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(max_length=255, unique=True)
    description = models.TextField()
    difficulty_level = models.IntegerField(choices=DIFFICULTY_LEVEL)
    craft = models.IntegerField(choices=CRAFT)
    yarn_weight = models.IntegerField(choices=WEIGHT)
    size = models.IntegerField(choices=SIZE, blank=True, null=True)
    category = models.IntegerField(choices=CATEGORY, blank=True, null=True)
    image = CloudinaryField('image', default='placeholder')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class PatternHooksNeedle(models.Model):
    pattern = models.ForeignKey(
        Pattern, on_delete=models.CASCADE,
        related_name="pattern_hooks_needles")
    type = models.IntegerField(choices=HOOK_NEEDLE_TYPE)
    hook_size = models.IntegerField(choices=HOOK_SIZE, blank=True, null=True)
    needle_size = models.IntegerField(
        choices=NEEDLE_SIZE, blank=True, null=True)

    def __str__(self):
        type_display = dict(HOOK_NEEDLE_TYPE).get(self.type, "Unknown")
        return (
            f"{type_display} for {self.pattern.title} "
            f"by {self.pattern.author.username}"
        )


class Favourite(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name="favourites")
    pattern = models.ManyToManyField(
        Pattern, blank=True, related_name="favourites")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="comments"
    )
    pattern = models.ForeignKey(
        Pattern, on_delete=models.CASCADE, related_name="comments")
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

patterns/forms.py
from django import forms
from django.utils.text import slugify
from .models import Pattern, PatternHooksNeedle, Comment
from django.forms import inlineformset_factory


class PatternForm(forms.ModelForm):
    class Meta:
        model = Pattern
        fields = ['title', 'description', 'difficulty_level',
                  'craft', 'yarn_weight', 'size', 'category', 'image']
        error_messages = {
            'title': {
                'unique': (
                    "A pattern with this title already exists. "
                    "Please choose a different title."
                ),
            },
        }

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.slug = slugify(instance.title)
        if commit:
            instance.save()
        return instance


class PatternHooksNeedleForm(forms.ModelForm):
    class Meta:
        model = PatternHooksNeedle
        fields = ['type', 'hook_size', 'needle_size']


PatternHooksNeedleFormSet = inlineformset_factory(
    Pattern,
    PatternHooksNeedle,
    fields=('type', 'hook_size', 'needle_size'),
    extra=1,
    can_delete=True
)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

patterns/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.views import generic
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from .models import Pattern, Favourite, Comment
from .forms import PatternForm, PatternHooksNeedleFormSet, CommentForm
from django.db.models import Q


class PatternList(generic.ListView):
    """
    View to list all patterns, with optional search functionality.
    Patterns are ordered by creation date in descending order.
    Pagination is set to 8 patterns per page.
    """
    queryset = Pattern.objects.all().order_by('-created_at')
    template_name = "patterns/index.html"
    paginate_by = 8

    def get_queryset(self):
        """
        Override the default queryset to include search functionality.
        Filters patterns by title or author's username if a search query is
        provided.
        """
        query = self.request.GET.get('q')
        if query:
            return Pattern.objects.filter(
                Q(title__icontains=query) | Q(
                    author__username__icontains=query)
            ).order_by('-created_at')
        return super().get_queryset()

    def get_context_data(self, **kwargs):
        """
        Add additional context to the template.
        If the user is authenticated, include their favourite patterns in the
        context.
        """
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            favourite = Favourite.objects.get(user=self.request.user)
            context['favourite_patterns'] = favourite.pattern.all()
        else:
            context['favourite_patterns'] = []
        context['search_query'] = self.request.GET.get('q', '')
        return context


def pattern_detail(request, slug):
    """
    View to display the details of a specific pattern.
    Includes hooks and needles associated with the pattern, comments, and a
    form to add new comments.
    If the user is authenticated, their favourite patterns are also included
    in the context.

    Args:
        request (HttpRequest): The request object.
        slug (str): The slug of the pattern to display.

    Returns:
        HttpResponse: The rendered template for the pattern detail page.
    """
    pattern = get_object_or_404(Pattern, slug=slug)
    hooks_needles = pattern.pattern_hooks_needles.all()

    needle_displayed = any(hn.needle_size is not None for hn in hooks_needles)
    hook_displayed = any(hn.hook_size is not None for hn in hooks_needles)

    comments = pattern.comments.all().order_by("-created_at")
    comment_count = pattern.comments.count()

    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.author = request.user
            comment.pattern = pattern
            comment.save()
            messages.success(request, "Comment posted successfully!")

    comment_form = CommentForm()

    favourite_patterns = []
    if request.user.is_authenticated:
        favourite = Favourite.objects.get(user=request.user)
        favourite_patterns = favourite.pattern.all()

    context = {
        'pattern': pattern,
        'hooks_needles': hooks_needles,
        'needle_displayed': needle_displayed,
        'hook_displayed': hook_displayed,
        'favourite_patterns': favourite_patterns,
        "comments": comments,
        "comment_count": comment_count,
        "comment_form": comment_form,
    }
    return render(request, 'patterns/pattern_detail.html', context)


@login_required
def toggle_favourite(request, slug):
    """
    View to add or remove a pattern from the user's favourites.
    If the pattern is already in the user's favourites, it will be removed.
    If the pattern is not in the user's favourites, it will be added.

    Args:
        request (HttpRequest): The request object.
        pattern_id (int): The ID of the pattern to toggle in favourites.

    Returns:
        HttpResponseRedirect: Redirects to the pattern detail page.
    """
    pattern = get_object_or_404(Pattern, slug=slug)
    favourite = Favourite.objects.get(user=request.user)

    if favourite.pattern.filter(id=pattern.id).exists():
        favourite.pattern.remove(pattern)
        messages.success(request, f"{pattern.title} removed from favourites.")
    else:
        favourite.pattern.add(pattern)

    return HttpResponseRedirect(
        request.META.get(
            'HTTP_REFERER', reverse('pattern_detail', args=[slug])
        )
    )


@login_required
def favourite_view(request):
    """
    View to display the user's favourite patterns.
    Retrieves the patterns that the user has marked as favourites and displays
    them in a list.

    Args:
        request (HttpRequest): The request object.

    Returns:
        HttpResponse: The rendered template for the favourite patterns page.
    """
    favourite = Favourite.objects.get(user=request.user)
    patterns = favourite.pattern.all()
    return render(request, 'favourite/favourite.html', {'patterns': patterns})


@login_required
def edit_comment(request, slug, comment_id):
    """
    Handle the editing of a comment on a pattern.
    This view handles the POST request to edit an existing comment on a
    pattern.
    It ensures that the comment belongs to the user making the request and that
    the form data is valid before saving the updated comment.
    Args:
        request (HttpRequest): The HTTP request object.
        slug (str): The slug of the pattern to which the comment belongs.
        comment_id (int): The ID of the comment to be edited.
    Returns:
        HttpResponseRedirect: Redirects to the pattern detail page after
        processing the form.
    """
    if request.method == "POST":

        pattern = get_object_or_404(Pattern, slug=slug)
        comment = get_object_or_404(Comment, pk=comment_id)
        comment_form = CommentForm(data=request.POST, instance=comment)

        if comment_form.is_valid() and comment.author == request.user:
            comment = comment_form.save(commit=False)
            comment.pattern = pattern
            comment.save()
            messages.add_message(request, messages.SUCCESS, 'Comment Updated!')
        else:
            messages.add_message(
                request, messages.ERROR, 'Error updating comment!'
            )

    return HttpResponseRedirect(reverse('pattern_detail', args=[slug]))


@login_required
def delete_comment(request, slug, comment_id):
    """
    Delete a comment if the request user is the author of the comment.
    Args:
        request (HttpRequest): The HTTP request object.
        slug (str): The slug of the pattern to which the comment belongs.
        comment_id (int): The ID of the comment to be deleted.
    Returns:
        HttpResponseRedirect: Redirects to the pattern detail page.
    Raises:
        Http404: If the comment with the given ID does not exist.
    """
    comment = get_object_or_404(Comment, pk=comment_id)

    if comment.author == request.user:
        comment.delete()
        messages.add_message(request, messages.SUCCESS, 'Comment deleted!')
    else:
        messages.add_message(
            request, messages.ERROR, 'You can only delete your own comments!'
        )

    return HttpResponseRedirect(reverse('pattern_detail', args=[slug]))


@login_required
def post_pattern(request):
    """
    Handle the posting of a new pattern.
    This view handles both GET and POST requests. On GET requests, it renders
    a form for creating a new pattern. On POST requests, it processes the form
    data and saves the new pattern if the form is valid.
    Args:
        request (HttpRequest): The HTTP request object.
    Returns:
        HttpResponse: The HTTP response object with the rendered template or a
        redirect.
    Raises:
        Exception: If there is an error while saving the pattern.
    Templates:
        patterns/post_pattern.html: The template for posting a new pattern.
    Context:
        form (PatternForm): The form for creating a new pattern.
        formset (PatternHooksNeedleFormSet): The formset for adding hooks and
        needles to the pattern.
    """
    if request.method == "POST":
        form = PatternForm(request.POST, request.FILES)
        formset = PatternHooksNeedleFormSet(request.POST)

        if form.is_valid() and formset.is_valid():
            try:
                pattern = form.save(commit=False)
                pattern.author = request.user
                pattern.save()
                formset.instance = pattern
                formset.save()
                messages.success(request, "Pattern posted successfully!")
                return redirect('pattern_detail', slug=pattern.slug)
            except Exception as e:
                messages.error(request, f"Error posting pattern: {e}")
        else:
            messages.error(request, "Please correct the errors below.")
    else:
        form = PatternForm()
        formset = PatternHooksNeedleFormSet()
    return render(
        request,
        'patterns/post_pattern.html',
        {'form': form, 'formset': formset}
    )

patterns/templates/patterns/index.html
{% extends "base.html" %}
{% load static %}
{% load cloudinary %}

{% block content %}

<!-- index.html content starts here -->
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <h1 class="display-4 text-center">Patterns</h1>
        </div>

        <!-- Search Bar -->
        <div class="col-12 mb-4 d-flex justify-content-center">
            <form method="get" action="{% url 'home' %}" class="w-50">
                <div class="input-group">
                    <label for="search" class="sr-only">Search for patterns or authors</label>
                    <input type="text" id="search" name="q" class="form-control" placeholder="Search for patterns or authors" value="{{ search_query }}">
                    <button class="btn btn-primary" type="submit">Search</button>
                </div>
            </form>
        </div>

        <!-- Pattern Entries Column -->
        <div class="col-12">
            <div class="row">
                {% for pattern in object_list %}
                <div class="col-lg-3 col-md-4 col-sm-6 col-12 mb-4">
                    <div class="card">
                        <a href="{% url 'pattern_detail' pattern.slug %}" class="post-link">
                            {% if "placeholder" in pattern.image.url %}
                            <img src="{% static 'images/default.jpg' %}" class="card-img-top img-fluid" alt="placeholder for pattern image">
                            {% else %}
                            {% cloudinary pattern.image alt=pattern.title quality="auto" format="webp" class="card-img-top img-fluid"%}
                            {% endif %}
                        </a>
                        <div class="card-body">
                            <div class="d-flex justify-content-between">
                                <a href="{% url 'pattern_detail' pattern.slug %}" class="post-link me-5">
                                    <h2 class="card-title">{{ pattern.title }}</h2>
                                </a>
                                {% if user.is_authenticated %}
                                <form method="post" action="{% url 'toggle_favourite' pattern.slug %}">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-primary index-button">
                                        <span class="d-none d-lg-inline">
                                            {% if pattern in favourite_patterns %}
                                                <i class="fa-solid fa-heart"></i> In your Favourite
                                            {% else %}
                                                <i class="fa-regular fa-heart"></i> Add to Favourite
                                            {% endif %}
                                        </span>
                                        <span class="d-inline d-lg-none">
                                            {% if pattern in favourite_patterns %}
                                                <i class="fa-solid fa-heart"></i>
                                            {% else %}
                                                <i class="fa-regular fa-heart"></i>
                                            {% endif %}
                                        </span>
                                    </button>
                                </form>
                                {% endif %}
                            </div>

                            <hr>

                            <div class="d-flex justify-content-between">
                                <p class="card-text text-muted h6 me-3">
                                    {{ pattern.author.username }}
                                </p>
                                <p class="card-text text-muted h6">
                                    {{ pattern.created_at|date:"F j, Y" }}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo; PREVIOUS</span>
                </a>
            </li>
            {% endif %}
            {% for num in page_obj.paginator.page_range %}
            <li class="page-item {% if page_obj.number == num %}active{% endif %}">
                <a class="page-link" href="?page={{ num }}">{{ num }}</a>
            </li>
            {% endfor %}
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">NEXT &raquo;</span>
                </a>
            </li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>

<!-- index.html content ends here -->
{% endblock %}

patterns/templates/patterns/pattern_detail.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load cloudinary %}

{% block title %}{{ pattern.title }}{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="d-flex flex-column flex-sm-row justify-content-between">
                <h1 class="display-4">{{ pattern.title }}</h1>
                {% if user.is_authenticated and pattern.author != user %}
                <form method="post" action="{% url 'toggle_favourite' pattern.slug %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary mt-3">
                        {% if pattern in favourite_patterns %}
                            <i class="fa-solid fa-heart"></i> In your Favourite
                        {% else %}
                            <i class="fa-regular fa-heart"></i> Add to Favourite
                        {% endif %}
                    </button>
                </form>
                {% elif not user.is_authenticated %}
                <p class="mt-3"><a href="{% url 'account_login' %}">Log in</a> to add this pattern to your favourite.</p>
                {% endif %}
            </div>
            <div class="d-flex justify-content-between">
                <p class="text-muted text-mb">by {{ pattern.author.username }}</p>
                <p class="text-muted text-mb">{{ pattern.created_at|date:"F j, Y" }}</p>
            </div>
            <hr>
            <div class="pattern-details row d-flex flex-wrap flex-md-nowrap">
                <div class="col-md-4">
                    {% if "placeholder" in pattern.image.url %}
                        <img src="{% static 'images/default.jpg' %}" alt="placeholder for pattern image" class="img-fluid mb-4 pattern-image">
                    {% else %}
                        {% cloudinary pattern.image alt=pattern.title quality="auto" format="webp" class="img-fluid mb-4 pattern-image"%}
                    {% endif %}
                </div>
                <div class="col-md-8">
                    <h3>Description</h3>
                    <p>{{ pattern.description }}</p>
                    <h3>Details</h3>
                    <table class="table">
                        <tr>
                            <th>Difficulty Level</th>
                            <td>{{ pattern.get_difficulty_level_display }}</td>
                        </tr>
                        <tr>
                            <th>Craft</th>
                            <td>{{ pattern.get_craft_display }}</td>
                        </tr>
                        <tr>
                            <th>Yarn Weight</th>
                            <td>{{ pattern.get_yarn_weight_display }}</td>
                        </tr>
                        <tr>
                            <th>Size</th>
                            <td>{{ pattern.get_size_display }}</td>
                        </tr>
                        <tr>
                            <th>Category</th>
                            <td>{{ pattern.get_category_display }}</td>
                        </tr>
                        {% if needle_displayed %}
                            <tr>
                                <th>Needle Size</th>
                                <td>
                                    {% for hook_needle in hooks_needles %}
                                        {% if hook_needle.get_needle_size_display %}
                                            {{ hook_needle.get_needle_size_display }}{% if not forloop.last %}<br>{% endif %}
                                        {% endif %}
                                    {% endfor %}
                                </td>
                            </tr>
                        {% endif %}
                        {% if hook_displayed %}
                            <tr>
                                <th>Hook Size</th>
                                <td>
                                    {% for hook_needle in hooks_needles %}
                                        {% if hook_needle.get_hook_size_display %}
                                            {{ hook_needle.get_hook_size_display }}{% if not forloop.last %}<br>{% endif %}
                                        {% endif %}
                                    {% endfor %}
                                </td>
                            </tr>
                        {% endif %}
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- Displaying count of comments -->
  <div class="row">
    <div class="col-12">
      <strong class="text-secondary">
        <i class="fa-solid fa-comments"></i> {{ comment_count }}
      </strong>
    </div>
    <div class="col-12">
      <hr>
    </div>
  </div>
  <!-- Displaying Comments -->
  <div class="row">
    <div class="col-md-8 card bg-trans mb-4 mt-3 ">
      <h3>Comments:</h3>
      <div class="card-body">
        {% for comment in comments %}
        <div class="p-2">
          <p>
            {{ comment.author }}
            <span>
              {{ comment.created_at }}
            </span> wrote:
          </p>
          <div id="comment{{ comment.id }}">
            {{ comment.content | linebreaks }}
          </div>
            {% if user.is_authenticated and comment.author == user %}
                <button class="btn btn-primary btn-edit" data-comment-id="{{ comment.id }}">Edit</button>
                <button class="btn btn-secondary btn-delete" data-comment-id="{{ comment.id }}">Delete</button>
            {% endif %}
        </div>
        <!-- Our for loop ends here -->
        {% endfor %}
      </div>
    </div>
    <!-- Creating New Comments -->
    <div class="col-md-4 card mt-3 mb-4">
        <div class="card-body">
            {% if user.is_authenticated %}
            <h3>Leave a comment:</h3>
            <p>Posting as: {{ user.username }}</p>
            <form id="commentForm" method="post">
            {{ comment_form | crispy }}
            {% csrf_token %}
            <button id="submitButton" type="submit"
              class="btn btn-secondary btn-lg">Submit</button>
          </form>
          {% else %}
          <p><a href="{% url 'account_login' %}">Log in</a> to leave a comment</p>
          {% endif %}
        </div>
      </div>
  </div>
</div>

<!-- Delete confirmation modal -->
<div class="modal fade" id="deleteModal" tabindex="-1"
  aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"
          id="deleteModalLabel">Delete comment?</h5>
        <button type="button" class="btn-close"
          data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete your comment?
        This action cannot be undone.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary"
          data-bs-dismiss="modal">Close</button>
        <a id="deleteConfirm" href="#" class="btn
          btn-danger">Delete</a>
      </div>
    </div>
  </div>
</div>

{% endblock %}

{% block extras %}
<script src="{% static 'js/comments.js' %}"></script>
{% endblock %}